server:
  port: 7071
eureka:
  instance:
    prefer-ip-address: true
  # 生产环境中官方是不建议修改默认配置，因为那样会破坏 eureka server 的保护模式
  server:
    # 关闭保护模式（生产环境不建议修改）
    enable-self-preservation: false
    # 清理间隔（默认是60 * 1000 毫秒）（生产环境不建议修改）
    eviction-interval-timer-in-ms: 60000
    # Eureka 拉取服务列表时间（默认：30秒）（生产环境不建议修改）
    remote-region-registry-fetch-interval: 5
  client:
    # eureka server 没必要自己把自己注册上去，所以可以设置成 false
    register-with-eureka: false
    # 是否从Eureka Server上获取注册信息，默认为true，此处建议修改成 false （单机设置的意义不大，如果设置成 true 启动会去抓取一次注册表，获取不到更新缓存就会出错（该错误不影响 eureka 正常使用））
    fetch-registry: false
    service-url:
      # 默认注册地址 this.serviceUrl.put("defaultZone", "http://localhost:8761/eureka/");
      # 划重点：此处的 defaultZone 千万别写成 default-zone
      defaultZone: http://localhost:${server.port}/eureka/
      # 从 Eureka 服务器端获取注册信息的间隔时间（默认：30秒）
    registry-fetch-interval-seconds: 5